name: Run script and commit CSV

on: 
  push:
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: Use Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '18'

        - name: Install dependencies
          run: npm ci

        - name: Run script
          run: node index.js
          env:
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: Commit and push if it changed
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add projects.csv
            git diff --quiet && git diff --staged --quiet || git commit -m "Update projects.csv"
            git push